version: "3"
services:
  xunsearch:
    image: hightman/xunsearch:latest
    volumes:
      - ./xunsearch/data:/usr/local/xunsearch/data
    networks:
      - default

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8099:8080"
    volumes:
        - ./jenkins:/var/jenkins_home:rw
    networks:
      - default

  swaggerui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8010:8080"
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  consul:
    image: consul:latest
    command: "agent -server -bootstrap -ui -node=consul -client=0.0.0.0"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    ports:
      - "8500:8500"
    networks:
      - default

networks:
  default:
